<?php

namespace Database\Seeders;

use App\Models\BelanjaRekening;
use Illuminate\Database\Seeder;

class BelanjaRekeningSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            ['kode' => "5", 'uraian' => "", 'level' => 1],
            ['kode' => "5.1", 'uraian' => "Belanja Pegawai", 'level' => 2],
            ['kode' => "5.1.1", 'uraian' => "Penghasilan Tetap dan Tunjangan Kepala Desa", 'level' => 3],
            ['kode' => "5.1.1.01", 'uraian' => "Penghasilan Tetap Kepala Desa", 'level' => 4],
            ['kode' => "5.1.1.02", 'uraian' => "Tunjangan Kepala Desa", 'level' => 4],
            ['kode' => "5.1.1.90", 'uraian' => "Tunjangan Hari Raya Kepala Desa", 'level' => 4],
            ['kode' => "5.1.1.99", 'uraian' => "Penerimaan Lain-lain Kepala Desa yang Sah", 'level' => 4],
            ['kode' => "5.1.2", 'uraian' => "Penghasilan Tetap dan Tunjangan Perangkat Desa", 'level' => 3],
            ['kode' => "5.1.2.01", 'uraian' => "Penghasilan Tetap Perangkat Desa", 'level' => 4],
            ['kode' => "5.1.2.02", 'uraian' => "Tunjangan Perangkat Desa", 'level' => 4],
            ['kode' => "5.1.2.90", 'uraian' => "Tunjangan Hari Raya Perangkat Desa", 'level' => 4],
            ['kode' => "5.1.2.91", 'uraian' => "Penghasilan Tetap Staf Perangkat Desa", 'level' => 4],
            ['kode' => "5.1.2.92", 'uraian' => "Tunjangan Staf Perangkat Desa", 'level' => 4],
            ['kode' => "5.1.2.93", 'uraian' => "Tunjangan Hari Raya Staf Perangkat Desa", 'level' => 4],
            ['kode' => "5.1.2.94", 'uraian' => "Penghasilan Tetap Staf BPD", 'level' => 4],
            ['kode' => "5.1.2.95", 'uraian' => "Tunjangan Staf BPD", 'level' => 4],
            ['kode' => "5.1.2.96", 'uraian' => "Tunjangan Hari Raya Staf BPD", 'level' => 4],
            ['kode' => "5.1.2.99", 'uraian' => "Penerimaan Lain-lain Perangkat Desa yang Sah", 'level' => 4],
            ['kode' => "5.1.3", 'uraian' => "Jaminan Sosial Kepala Desa dan Perangkat Desa", 'level' => 3],
            ['kode' => "5.1.3.01", 'uraian' => "Jaminan Kesehatan Kepala Desa", 'level' => 4],
            ['kode' => "5.1.3.02", 'uraian' => "Jaminan Kesehatan Perangkat Desa", 'level' => 4],
            ['kode' => "5.1.3.03", 'uraian' => "Jaminan Ketenagakerjaan Kepala Desa", 'level' => 4],
            ['kode' => "5.1.3.04", 'uraian' => "Jaminan Ketenagakerjaan Perangkat Desa", 'level' => 4],
            ['kode' => "5.1.3.90", 'uraian' => "Jaminan Ketenagakerjaan Staf Perangkat Desa", 'level' => 4],
            ['kode' => "5.1.3.91", 'uraian' => "Jaminan Ketenagakerjaan Staf BPD", 'level' => 4],
            ['kode' => "5.1.3.99", 'uraian' => "jaminan Sosial Lainnya", 'level' => 4],
            ['kode' => "5.1.4", 'uraian' => "Tunjangan BPD", 'level' => 3],
            ['kode' => "5.1.4.01", 'uraian' => "Tunjangan Kedudukan BPD", 'level' => 4],
            ['kode' => "5.1.4.02", 'uraian' => "Tunjangan Kinerja BPD", 'level' => 4],
            ['kode' => "5.1.4.90", 'uraian' => "Tunjangan Hari Raya BPD", 'level' => 4],
            ['kode' => "5.1.4.91", 'uraian' => "Jaminan Ketenagakerjaan BPD", 'level' => 4],
            ['kode' => "5.1.4.99", 'uraian' => "Jaminan Sosial Lainnya", 'level' => 4],
            ['kode' => "5.1.5", 'uraian' => "Jaminan Sosial BPD", 'level' => 3],
            ['kode' => "5.1.5.01", 'uraian' => "Jaminan Kesehatan Anggota BPD", 'level' => 4],
            ['kode' => "5.1.5.02", 'uraian' => "Jaminan Ketenagakerjaan Anggota BPD", 'level' => 4],
            ['kode' => "5.2", 'uraian' => "Belanja Barang dan Jasa", 'level' => 2],
            ['kode' => "5.2.1", 'uraian' => "Belanja Barang Perlengkapan", 'level' => 3],
            ['kode' => "5.2.1.01", 'uraian' => "Belanja Alat Tulis Kantor dan Benda Pos", 'level' => 4],
            ['kode' => "5.2.1.02", 'uraian' => "Belanja Perlengkapan Alat-alat Listrik", 'level' => 4],
            ['kode' => "5.2.1.03", 'uraian' => "Belanja Perlengkapan Alat Rumah Tangga dan Bahan Kebersihan", 'level' => 4],
            ['kode' => "5.2.1.04", 'uraian' => "Belanja Bahan Bakar Minyak/Gas/Isi Ulang Tabung Pemadam Kebakaran", 'level' => 4],
            ['kode' => "5.2.1.05", 'uraian' => "Belanja Barang Cetak dan Penggandaan", 'level' => 4],
            ['kode' => "5.2.1.06", 'uraian' => "Belanja Barang Konsumsi (Makan/Minum)", 'level' => 4],
            ['kode' => "5.2.1.07", 'uraian' => "Belanja Bahan Material", 'level' => 4],
            ['kode' => "5.2.1.08", 'uraian' => "Belanja Bendera/Umbul-umbul/Spanduk", 'level' => 4],
            ['kode' => "5.2.1.09", 'uraian' => "Belanja Pakaian Dinas/Seragam/Atribut", 'level' => 4],
            ['kode' => "5.2.1.10", 'uraian' => "Belanja Bahan Obat-obatan", 'level' => 4],
            ['kode' => "5.2.1.11", 'uraian' => "Belanja Pakan Hewan, Obat-obatan Hewan", 'level' => 4],
            ['kode' => "5.2.1.12", 'uraian' => "Belanja Pupuk/Obat-obatan Pertanian", 'level' => 4],
            ['kode' => "5.2.1.90", 'uraian' => "Belanja Hadiah Berupa Barang untuk lomba-lomba", 'level' => 4],
            ['kode' => "5.2.1.91", 'uraian' => "Belanja Hadiah Berupa Uang untuk lomba-lomba", 'level' => 4],
            ['kode' => "5.2.1.92", 'uraian' => "Belanja Bibit Perikanan/Perkebunan/Peternakan dan Pertanian", 'level' => 4],
            ['kode' => "5.2.1.99", 'uraian' => "Belanja Barang Perlengkapan Lainnya", 'level' => 4],
            ['kode' => "5.2.2", 'uraian' => "Belanja Jasa Honorarium", 'level' => 3],
            ['kode' => "5.2.2.01", 'uraian' => "Belanja Jasa Honorarium Tim Pelaksana Kegiatan", 'level' => 4],
            ['kode' => "5.2.2.02", 'uraian' => "Belanja Jasa Honorarium Pembantu Tugas Umum Desa/Operator", 'level' => 4],
            ['kode' => "5.2.2.03", 'uraian' => "Belanja Jasa Honorarium/Insentif Pelayanan Desa", 'level' => 4],
            ['kode' => "5.2.2.04", 'uraian' => "Belanja Jasa Honorarium Tenaga Ahli/Profesi/Konsultan/Narasumber", 'level' => 4],
            ['kode' => "5.2.2.05", 'uraian' => "Belanja Jasa Honorarium Petugas", 'level' => 4],
            ['kode' => "5.2.2.06", 'uraian' => "Belanja Jasa Honorarium PKPKD dan PPKD", 'level' => 4],
            ['kode' => "5.2.2.07", 'uraian' => "Belanja Jasa Honorarium Staf Administrasi BPD", 'level' => 4],
            ['kode' => "5.2.2.08", 'uraian' => "Belanja Jasa Uang Saku Pelatihan/Seminar/Bimbingan Teknis", 'level' => 4],
            ['kode' => "5.2.2.90", 'uraian' => "Belanja Honorarium Petugas Pendata PBB", 'level' => 4],
            ['kode' => "5.2.2.91", 'uraian' => "Belanja Jasa Honorarium Pengelola Aset Desa", 'level' => 4],
            ['kode' => "5.2.2.92", 'uraian' => "Belanja Honorarium Tim Penyertaan Modal Desa", 'level' => 4],
            ['kode' => "5.2.2.93", 'uraian' => "Belanja Honorarium TIM Penyusun RPJMDesa", 'level' => 4],
            ['kode' => "5.2.2.94", 'uraian' => "Belanja Honorarium TIM Penyusun RKPDesa", 'level' => 4],
            ['kode' => "5.2.2.95", 'uraian' => "Belanja Honorarium Petugas Sopir Ambulance Desa", 'level' => 4],
            ['kode' => "5.2.2.96", 'uraian' => "Belanja Honorarium Petugas", 'level' => 4],
            ['kode' => "5.2.2.99", 'uraian' => "Belanja Jasa Honorarium Lainnya", 'level' => 4],
            ['kode' => "5.2.3", 'uraian' => "Belanja Perjalanan Dinas", 'level' => 3],
            ['kode' => "5.2.3.01", 'uraian' => "Belanja Perjalanan Dinas Dalam Kabupaten/Kota", 'level' => 4],
            ['kode' => "5.2.3.02", 'uraian' => "Belanja Perjalanan Dinas Luar Kabupaten/Kota", 'level' => 4],
            ['kode' => "5.2.3.03", 'uraian' => "Belanja Kursus Pelatihan", 'level' => 4],
            ['kode' => "5.2.4", 'uraian' => "Belanja Jasa Sewa", 'level' => 3],
            ['kode' => "5.2.4.01", 'uraian' => "Belanja Jasa Sewa Bangunan/Gedung/Ruang", 'level' => 4],
            ['kode' => "5.2.4.02", 'uraian' => "Belanja Jasa Sewa Peralatan/Perlengkapan", 'level' => 4],
            ['kode' => "5.2.4.03", 'uraian' => "Belanja Jasa Sewa Sarana Mobilitas", 'level' => 4],
            ['kode' => "5.2.4.99", 'uraian' => "Belanja Jasa Sewa Lainnya", 'level' => 4],
            ['kode' => "5.2.5", 'uraian' => "Belanja Operasional Perkantoran", 'level' => 3],
            ['kode' => "5.2.5.01", 'uraian' => "Belanja Jasa Langganan Listrik", 'level' => 4],
            ['kode' => "5.2.5.02", 'uraian' => "Belanja Jasa Langganan Air Bersih", 'level' => 4],
            ['kode' => "5.2.5.03", 'uraian' => "Belanja Jasa Langganan Majalah/Surat Kabar", 'level' => 4],
            ['kode' => "5.2.5.04", 'uraian' => "Belanja Jasa Langganan Telepon", 'level' => 4],
            ['kode' => "5.2.5.05", 'uraian' => "Belanja Jasa Langganan Internet", 'level' => 4],
            ['kode' => "5.2.5.06", 'uraian' => "Belanja Jasa Kurir/Pos/Giro", 'level' => 4],
            ['kode' => "5.2.5.07", 'uraian' => "Belanja Jasa Perpanjangan Ijin/Pajak", 'level' => 4],
            ['kode' => "5.2.5.08", 'uraian' => "Belanja Insentif/Operasional RT/RW", 'level' => 4],
            ['kode' => "5.2.5.90", 'uraian' => "Belanja Jasa Transaksi Keuangan ( Admin Bank Dll)", 'level' => 4],
            ['kode' => "5.2.5.91", 'uraian' => "Belanja Sertifikasi", 'level' => 4],
            ['kode' => "5.2.5.92", 'uraian' => "Belanja Dekorasi dan Dokumentasi", 'level' => 4],
            ['kode' => "5.2.5.99", 'uraian' => "Belanja Operasional Perkantoran lainnya", 'level' => 4],
            ['kode' => "5.2.6", 'uraian' => "Belanja Pemeliharaan", 'level' => 3],
            ['kode' => "5.2.6.01", 'uraian' => "Belanja Pemeliharaan Mesin dan Peralatan Berat", 'level' => 4],
            ['kode' => "5.2.6.02", 'uraian' => "Belanja Pemeliharaan Kendaraan Bermotor", 'level' => 4],
            ['kode' => "5.2.6.03", 'uraian' => "Belanja Pemeliharaan Peralatan", 'level' => 4],
            ['kode' => "5.2.6.04", 'uraian' => "Belanja Pemeliharaan Bangunan", 'level' => 4],
            ['kode' => "5.2.6.05", 'uraian' => "Belanja Pemeliharaan Jalan", 'level' => 4],
            ['kode' => "5.2.6.06", 'uraian' => "Belanja Pemeliharaan Jembatan", 'level' => 4],
            ['kode' => "5.2.6.07", 'uraian' => "Belanja Pemeliharaan Irigasi/Saluran Sungai/Embung/Air Bersih", 'level' => 4],
            ['kode' => "5.2.6.08", 'uraian' => "Belanja Pemeliharaan Jaringan dan Instalasi (Listrik, telepon, internet, komunikasi dll)", 'level' => 4],
            ['kode' => "5.2.6.99", 'uraian' => "Belanja Pemeliharaan Lainnya", 'level' => 4],
            ['kode' => "5.2.7", 'uraian' => "Belanja Barang dan Jasa yang Diserahkan kepada Masyarakat", 'level' => 3],
            ['kode' => "5.2.7.01", 'uraian' => "Belanja Bahan Perlengkapan untuk Diserahkan kepada Masyarakat", 'level' => 4],
            ['kode' => "5.2.7.02", 'uraian' => "Belanja Bantuan Mesin/Peralatan/Kendaraan untuk Diserahkan kepada Masyarakat", 'level' => 4],
            ['kode' => "5.2.7.03", 'uraian' => "Belanja Bantuan Bangunan untuk Diserahkan kepada Masyarakat", 'level' => 4],
            ['kode' => "5.2.7.04", 'uraian' => "Belanja Beasiswa Berprestasi/Masyarakat Miskin", 'level' => 4],
            ['kode' => "5.2.7.05", 'uraian' => "Belanja Bantuan Bibit Tanaman/Hewan/Ikan", 'level' => 4],
            ['kode' => "5.2.7.90", 'uraian' => "Belanja Bantuan Bahan dan Barang untuk masyarakat", 'level' => 4],
            ['kode' => "5.2.7.91", 'uraian' => "Belanja Barang dan Jasa yang diserahkan kepada kelompok", 'level' => 4],
            ['kode' => "5.2.7.99", 'uraian' => "Belanja Barang untuk Diserahkan kepada Masyarakat Lainnya", 'level' => 4],
            ['kode' => "5.3", 'uraian' => "Belanja Modal", 'level' => 2],
            ['kode' => "5.3.1", 'uraian' => "Belanja Modal Pengadaan Tanah", 'level' => 3],
            ['kode' => "5.3.1.01", 'uraian' => "Belanja Modal Pembebasan/Pembelian Tanah", 'level' => 4],
            ['kode' => "5.3.1.02", 'uraian' => "Belanja Modal Pembayaran Honorarium Tim Tanah", 'level' => 4],
            ['kode' => "5.3.1.03", 'uraian' => "Belanja Modal Pengukuran dan Pembuatan Sertifikat Tanah", 'level' => 4],
            ['kode' => "5.3.1.04", 'uraian' => "Belanja Modal Pengurukan dan Pematangan Tanah", 'level' => 4],
            ['kode' => "5.3.1.05", 'uraian' => "Belanja Modal Perjalanan Pengadaan Tanah", 'level' => 4],
            ['kode' => "5.3.1.06", 'uraian' => "Belanja Modal Pembayaran Iuran Jaminan Ketenagakerjaan bagi Pekerja (Pengurukan Pematangan Tanah)", 'level' => 4],
            ['kode' => "5.3.1.99", 'uraian' => "Belanja Modal Pengadaan Tanah Lainnya", 'level' => 4],
            ['kode' => "5.3.2", 'uraian' => "Belanja Modal Pengadaan Peralatan, Mesin dan Alat Berat", 'level' => 3],
            ['kode' => "5.3.2.01", 'uraian' => "Belanja Modal Pembayaran Honor Tim Pelaksana Kegiatan (PM)", 'level' => 4],
            ['kode' => "5.3.2.02", 'uraian' => "Belanja Modal Peralatan Elektronik dan Alat Studio", 'level' => 4],
            ['kode' => "5.3.2.03", 'uraian' => "Belanja Modal Peralatan Komputer", 'level' => 4],
            ['kode' => "5.3.2.04", 'uraian' => "Belanja Modal Peralatan Mebelair dan Aksesoris Ruangan", 'level' => 4],
            ['kode' => "5.3.2.05", 'uraian' => "Belanja Modal Peralatan Dapur", 'level' => 4],
            ['kode' => "5.3.2.06", 'uraian' => "Belanja Modal Peralatan Alat Ukur", 'level' => 4],
            ['kode' => "5.3.2.07", 'uraian' => "Belanja Modal Peralatan Rambu-rambu/Patok Tanah", 'level' => 4],
            ['kode' => "5.3.2.08", 'uraian' => "Belanja Modal Peralatan Khusus Kesehatan", 'level' => 4],
            ['kode' => "5.3.2.09", 'uraian' => "Belanja Modal Peralatan Khusus Pertanian/Peternakan/Perikanan", 'level' => 4],
            ['kode' => "5.3.2.10", 'uraian' => "Belanja Modal Mesin", 'level' => 4],
            ['kode' => "5.3.2.11", 'uraian' => "Belanja Modal Pengadaan Alat-alat Berat", 'level' => 4],
            ['kode' => "5.3.2.99", 'uraian' => "Belanja Modal Peralatan, Mesin dan Alat Berat Lainnya", 'level' => 4],
            ['kode' => "5.3.3", 'uraian' => "Belanja Modal Kendaraan", 'level' => 3],
            ['kode' => "5.3.3.01", 'uraian' => "Belanja Modal Honor Tim Pengadaan (Kendaraan)", 'level' => 4],
            ['kode' => "5.3.3.02", 'uraian' => "Belanja Modal Kendaraan Darat Bermotor", 'level' => 4],
            ['kode' => "5.3.3.03", 'uraian' => "Belanja Modal Kendaaran Darat Tidak Bermotor", 'level' => 4],
            ['kode' => "5.3.3.04", 'uraian' => "Belanja Modal Kendaraan Air Bermotor", 'level' => 4],
            ['kode' => "5.3.3.05", 'uraian' => "Belanja Modal Kendaraan Air Tidak Bermotor", 'level' => 4],
            ['kode' => "5.3.3.99", 'uraian' => "Belanja Modal Kendaraan Lainnya", 'level' => 4],
            ['kode' => "5.3.4", 'uraian' => "Belanja Modal Gedung, Bangunan dan Taman", 'level' => 3],
            ['kode' => "5.3.4.01", 'uraian' => "Belanja Modal Gedung, Bangunan, Taman - Honor Pelaksana Kegiatan", 'level' => 4],
            ['kode' => "5.3.4.02", 'uraian' => "Belanja Modal Gedung, Bangunan, Taman - Upah Tenaga Kerja", 'level' => 4],
            ['kode' => "5.3.4.03", 'uraian' => "Belanja Modal Gedung, Bangunan, Taman - Bahan Baku/Material", 'level' => 4],
            ['kode' => "5.3.4.04", 'uraian' => "Belanja Modal Gedung, Bangunan, Taman - Sewa Peralatan", 'level' => 4],
            ['kode' => "5.3.4.05", 'uraian' => "Belanja Modal Gedung, Bangunan, Taman - Administrasi Kegiatan", 'level' => 4],
            ['kode' => "5.3.4.06", 'uraian' => "Belanja Modal Pembayaran Iuran Jaminan Ketenagakerjaan bagi Pekerja", 'level' => 4],
            ['kode' => "5.3.5", 'uraian' => "Belanja Modal Jalan/Prasarana Jalan", 'level' => 3],
            ['kode' => "5.3.5.01", 'uraian' => "Belanja Modal Jalan - Honor Tim Pelaksana Kegiatan", 'level' => 4],
            ['kode' => "5.3.5.02", 'uraian' => "Belanja Modal Jalan - Upah Tenaga Kerja", 'level' => 4],
            ['kode' => "5.3.5.03", 'uraian' => "Belanja Modal Jalan - Bahan Baku/Material", 'level' => 4],
            ['kode' => "5.3.5.04", 'uraian' => "Belanja Modal Jalan - Sewa Peralatan", 'level' => 4],
            ['kode' => "5.3.5.05", 'uraian' => "Belanja Modal Jalan - Administrasi Kegiatan", 'level' => 4],
            ['kode' => "5.3.5.06", 'uraian' => "Belanja Modal Pembayaran Iuran Jaminan Ketenagakerjaan bagi Pekerja", 'level' => 4],
            ['kode' => "5.3.6", 'uraian' => "Belanja Modal Jembatan", 'level' => 3],
            ['kode' => "5.3.6.01", 'uraian' => "Belanja Modal Jembatan - Honor Pelaksana Kegiatan", 'level' => 4],
            ['kode' => "5.3.6.02", 'uraian' => "Belanja Modal Jembatan - Upah Tenaga Kerja", 'level' => 4],
            ['kode' => "5.3.6.03", 'uraian' => "Belanja Modal Jembatan - Bahan Baku/Material", 'level' => 4],
            ['kode' => "5.3.6.04", 'uraian' => "Belanja Modal Jembatan - Sewa Peralatan", 'level' => 4],
            ['kode' => "5.3.6.05", 'uraian' => "Belanja Modal Jembatan - Administrasi Kegiatan", 'level' => 4],
            ['kode' => "5.3.6.06", 'uraian' => "Belanja Modal Pembayaran Iuran Jaminan Ketenagakerjaan bagi Pekerja", 'level' => 4],
            ['kode' => "5.3.7", 'uraian' => "Belanja Modal Irigasi/Embung/Drainase/Air Limbah/Persampahan", 'level' => 3],
            ['kode' => "5.3.7.01", 'uraian' => "Belanja Modal Irigasi/Embung/Drainase/dll - Honor Tim Pelaksana Kegiatan", 'level' => 4],
            ['kode' => "5.3.7.02", 'uraian' => "Belanja Modal Irigasi/Embung/Drainase/dll - Upah Tenaga Kerja", 'level' => 4],
            ['kode' => "5.3.7.03", 'uraian' => "Belanja Modal Irigasi/Embung/Drainase/dll - Bahan Baku/Material", 'level' => 4],
            ['kode' => "5.3.7.04", 'uraian' => "Belanja Modal Irigasi/Embung/Drainase/dll - Sewa Peralatan", 'level' => 4],
            ['kode' => "5.3.7.05", 'uraian' => "Belanja Modal Irigasi/Embung/Drainase/dll - Administrasi Kegiatan", 'level' => 4],
            ['kode' => "5.3.7.06", 'uraian' => "Belanja Modal Pembayaran Iuran Jaminan Ketenagakerjaan bagi Pekerja", 'level' => 4],
            ['kode' => "5.3.8", 'uraian' => "Belanja Modal Jaringan/Instalasi", 'level' => 3],
            ['kode' => "5.3.8.01", 'uraian' => "Belanja Modal Jaringan/Instalasi - Honor Tim Pelaksana Kegiatan", 'level' => 4],
            ['kode' => "5.3.8.02", 'uraian' => "Belanja Modal Jaringan/Instalasi - Upah Tenaga Kerja", 'level' => 4],
            ['kode' => "5.3.8.03", 'uraian' => "Belanja Modal Jaringan/Instalasi - Bahan Baku/Material", 'level' => 4],
            ['kode' => "5.3.8.04", 'uraian' => "Belanja Modal Jaringan/Instalasi - Sewa Peralatan", 'level' => 4],
            ['kode' => "5.3.8.05", 'uraian' => "Belanja Modal Jaringan/Instalasi - Administrasi Kegiatan", 'level' => 4],
            ['kode' => "5.3.8.06", 'uraian' => "Belanja Modal Pembayaran Iuran Jaminan Ketenagakerjaan bagi Pekerja", 'level' => 4],
            ['kode' => "5.3.9", 'uraian' => "Belanja Modal Lainnya", 'level' => 3],
            ['kode' => "5.3.9.01", 'uraian' => "Belanja Khusus Pendidikan dan Perpustakaan", 'level' => 4],
            ['kode' => "5.3.9.02", 'uraian' => "Belanja Khusus Olahraga", 'level' => 4],
            ['kode' => "5.3.9.03", 'uraian' => "Belanja Modal Khusus Kesenian/Kebudayaan/Keagamaan", 'level' => 4],
            ['kode' => "5.3.9.04", 'uraian' => "Belanja Modal Tumbuhan/Tanaman", 'level' => 4],
            ['kode' => "5.3.9.05", 'uraian' => "Belanja Modal Hewan", 'level' => 4],
            ['kode' => "5.3.9.99", 'uraian' => "Belanja Modal Lainnya", 'level' => 4],
            ['kode' => "5.4", 'uraian' => "Belanja Tidak Terduga", 'level' => 2],
            ['kode' => "5.4.1", 'uraian' => "Belanja Tidak Terduga", 'level' => 3],
            ['kode' => "5.4.1.01", 'uraian' => "Belanja Tidak Terduga", 'level' => 4]
        ];

        $ids = [];
        foreach ($rows as $row) {
            $parentCode = str_contains($row['kode'], '.')
                ? substr($row['kode'], 0, strrpos($row['kode'], '.'))
                : null;

            $item = BelanjaRekening::updateOrCreate(
                ['kode' => $row['kode']],
                [
                    'uraian' => $row['uraian'],
                    'parent_id' => $parentCode ? ($ids[$parentCode] ?? null) : null,
                    'level' => $row['level'],
                    'is_active' => true,
                ]
            );
            $ids[$row['kode']] = $item->id;
        }

        $this->command?->info('Master rekening Belanja berhasil diisi: ' . count($rows) . ' rekening (termasuk induk).');
    }
}
