<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void {
        Schema::create('desa', function (Blueprint $t) { $t->id(); $t->string('nama'); $t->string('kecamatan')->nullable(); $t->string('kabupaten'); $t->string('provinsi'); $t->text('alamat')->nullable(); $t->string('website')->nullable(); $t->string('email')->nullable(); $t->string('logo')->nullable(); $t->timestamps(); });
        Schema::create('tahun_anggaran', function (Blueprint $t) { $t->id(); $t->unsignedSmallInteger('tahun')->unique(); $t->enum('status',['aktif','nonaktif'])->default('nonaktif'); $t->timestamps(); });
        foreach (['bidang','kegiatan','sub_kegiatan'] as $table) Schema::create($table, function (Blueprint $t) use ($table) { $t->id(); $t->foreignId('tahun_anggaran_id')->constrained('tahun_anggaran')->cascadeOnDelete(); if ($table === 'kegiatan') $t->foreignId('bidang_id')->constrained('bidang')->cascadeOnDelete(); if ($table === 'sub_kegiatan') $t->foreignId('kegiatan_id')->constrained('kegiatan')->cascadeOnDelete(); $t->string('kode'); $t->string('nama'); $t->unsignedInteger('urutan')->default(0); $t->enum('status_publikasi',['draft','dipublikasikan','tidak_dipublikasikan'])->default('draft'); $t->timestamps(); });
        Schema::create('pendapatan', function (Blueprint $t) { $t->id(); $t->foreignId('tahun_anggaran_id')->constrained('tahun_anggaran')->cascadeOnDelete(); $t->string('kode'); $t->string('kelompok'); $t->string('uraian'); $t->decimal('anggaran',18,2); $t->unsignedInteger('urutan')->default(0); $t->enum('status_publikasi',['draft','dipublikasikan','tidak_dipublikasikan'])->default('draft'); $t->timestamps(); });
        Schema::create('belanja', function (Blueprint $t) { $t->id(); $t->foreignId('tahun_anggaran_id')->constrained('tahun_anggaran')->cascadeOnDelete(); $t->foreignId('bidang_id')->nullable()->constrained('bidang')->nullOnDelete(); $t->foreignId('kegiatan_id')->nullable()->constrained('kegiatan')->nullOnDelete(); $t->foreignId('sub_kegiatan_id')->nullable()->constrained('sub_kegiatan')->nullOnDelete(); $t->string('kode'); $t->string('uraian'); $t->decimal('anggaran',18,2); $t->unsignedInteger('urutan')->default(0); $t->enum('status_publikasi',['draft','dipublikasikan','tidak_dipublikasikan'])->default('draft'); $t->timestamps(); });
        Schema::create('pembiayaan', function (Blueprint $t) { $t->id(); $t->foreignId('tahun_anggaran_id')->constrained('tahun_anggaran')->cascadeOnDelete(); $t->enum('jenis',['penerimaan','pengeluaran']); $t->string('kode'); $t->string('uraian'); $t->decimal('anggaran',18,2); $t->unsignedInteger('urutan')->default(0); $t->enum('status_publikasi',['draft','dipublikasikan','tidak_dipublikasikan'])->default('draft'); $t->timestamps(); });
        foreach (['pendapatan','belanja','pembiayaan'] as $jenis) Schema::create("realisasi_{$jenis}", function (Blueprint $t) use ($jenis) { $t->id(); $t->foreignId('tahun_anggaran_id')->constrained('tahun_anggaran')->cascadeOnDelete(); $t->foreignId("{$jenis}_id")->constrained($jenis)->cascadeOnDelete(); $t->unsignedTinyInteger('bulan'); $t->date('tanggal'); $t->decimal('nilai',18,2); $t->text('keterangan')->nullable(); $t->enum('status_publikasi',['draft','dipublikasikan','tidak_dipublikasikan'])->default('draft'); $t->timestamps(); $t->index(['tahun_anggaran_id','bulan']); });
        Schema::create('dokumen_publikasi', function (Blueprint $t) { $t->id(); $t->foreignId('tahun_anggaran_id')->constrained('tahun_anggaran')->cascadeOnDelete(); $t->string('kategori'); $t->string('judul'); $t->text('deskripsi')->nullable(); $t->string('file_path'); $t->enum('status_publikasi',['draft','dipublikasikan','tidak_dipublikasikan'])->default('draft'); $t->date('tanggal_publikasi')->nullable(); $t->timestamps(); });
        Schema::create('audit_logs', function (Blueprint $t) { $t->id(); $t->foreignId('user_id')->nullable()->constrained()->nullOnDelete(); $t->string('aktivitas'); $t->string('tabel')->nullable(); $t->unsignedBigInteger('record_id')->nullable(); $t->ipAddress('ip_address')->nullable(); $t->text('user_agent')->nullable(); $t->timestamp('created_at')->useCurrent(); });
    }
    public function down(): void { foreach (['audit_logs','dokumen_publikasi','realisasi_pembiayaan','realisasi_belanja','realisasi_pendapatan','pembiayaan','belanja','pendapatan','sub_kegiatan','kegiatan','bidang','tahun_anggaran','desa'] as $t) Schema::dropIfExists($t); }
};
