<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller; use App\Models\{Belanja,Bidang,Kegiatan,TahunAnggaran}; use Illuminate\Http\{Request,RedirectResponse}; use Illuminate\View\View;
class BelanjaController extends Controller {
 public function index():View{return view('admin.belanja.index',['items'=>Belanja::with(['tahunAnggaran','bidang','kegiatan'])->orderByDesc('tahun_anggaran_id')->orderBy('urutan')->paginate(12),'bidang'=>Bidang::with('kegiatan')->orderBy('urutan')->get(),'years'=>TahunAnggaran::orderByDesc('tahun')->get()]);}
 public function create():View{return view('admin.belanja.form',$this->data());} public function edit(Belanja $belanja):View{return view('admin.belanja.form',$this->data(['item'=>$belanja]));}
 public function store(Request $r):RedirectResponse{Belanja::create($this->valid($r));return to_route('admin.belanja.index')->with('success','Belanja ditambahkan.');} public function update(Request $r,Belanja $belanja):RedirectResponse{$belanja->update($this->valid($r));return to_route('admin.belanja.index')->with('success','Belanja diperbarui.');} public function destroy(Belanja $belanja):RedirectResponse{$belanja->delete();return back()->with('success','Belanja dihapus.');}
 public function publication(Belanja $belanja):RedirectResponse{$belanja->update(['status_publikasi'=>$belanja->status_publikasi==='dipublikasikan'?'draft':'dipublikasikan']);return back()->with('success','Status publikasi diperbarui.');}
 public function storeBidang(Request $r):RedirectResponse{$d=$r->validate(['tahun_anggaran_id'=>'required|exists:tahun_anggaran,id','kode'=>'required|max:50','nama'=>'required|max:255','urutan'=>'nullable|integer|min:0']);Bidang::create($d+['status_publikasi'=>'dipublikasikan']);return back()->with('success','Bidang ditambahkan.');}
 public function storeKegiatan(Request $r):RedirectResponse{$d=$r->validate(['bidang_id'=>'required|exists:bidang,id','kode'=>'required|max:50','nama'=>'required|max:255','urutan'=>'nullable|integer|min:0']);$d['tahun_anggaran_id']=Bidang::findOrFail($d['bidang_id'])->tahun_anggaran_id;Kegiatan::create($d+['status_publikasi'=>'dipublikasikan']);return back()->with('success','Kegiatan ditambahkan.');}
 private function data(array $a=[]):array{return $a+['years'=>TahunAnggaran::orderByDesc('tahun')->get(),'bidang'=>Bidang::with('kegiatan')->orderBy('urutan')->get()];} private function valid(Request $r):array{return $r->validate(['tahun_anggaran_id'=>'required|exists:tahun_anggaran,id','bidang_id'=>'nullable|exists:bidang,id','kegiatan_id'=>'nullable|exists:kegiatan,id','kode'=>'required|max:50','uraian'=>'required|max:255','anggaran'=>'required|numeric|min:0','urutan'=>'nullable|integer|min:0','status_publikasi'=>'required|in:draft,dipublikasikan']);}}
